# -*- coding: utf-8 -*-
"""Education Minister Resignation Campaign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dO3ZYmr1gLegNl462gy76N4zGuXrfEtx
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

# Listing petition signers in Session State
if "signatures_list" not in st.session_state:
    st.session_state.signatures_list = []

# Title of the app and the issue of the petition
st.title("✍️ Online Petition for Resignation")
st.subheader("Demand for the Resignation of Education Minister Dharmendra Pradhan")

st.markdown("""
> **Petition Statement:** > We, the citizens and students of India, are raising this petition to demand the immediate resignation
> of the Union Minister of Education, Dharmendra Pradhan, citing accountability for recent educational
> reforms, exam management, and policy execution concerns.
""")

st.divider()

# Creating a form that submits data at once
with st.form("petition_form", clear_on_submit=True):

    st.write("### Sign the Petition")

    # Name input box(using.upper() to convert letters to uppercase)
    raw_name = st.text_input("Enter Your Full Name (Will be saved in UPPERCASE)")
    name = raw_name.upper()

    # Signature input box(simple text,no conditions)
    signature = st.text_input("Digital Signature (Type your initials or full name as signature)")

    # Submit button
    submit_button = st.form_submit_button("Sign Petition")

# When the user presses the button
if submit_button:
    if name.strip() == "" or signature.strip() == "":
        st.error("❌ Please fill out both the Name and Signature fields!")
    else:
        # Save data to a list
        st.session_state.signatures_list.append({"Name": name, "Signature": signature})
        st.success(f"Thank you, {name}! Your signature has been recorded successfully. 🎉")

st.divider()

# Display a live count of petitions and a list of signers
st.subheader(f"📊 Live Status: {len(st.session_state.signatures_list)} Signatures Collected")

if st.session_state.signatures_list:
    # Display a list as a table
    st.table(st.session_state.signatures_list)

