# -*- coding: utf-8 -*-
"""Grade Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15i9AHGOrT1J12YhmUfrvQNkuHnqcI-8u
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st

# Heading of App
st.title("🎓Smart Grade Calculator")
st.write(" Drag the sliders to change marks.No keyword needed!")
st.divider()

# Sliders(from 0 to 100) for scoring without the kayboard
# min_value =0 ,max_value=100,value=50(starting value)

maths = st.slider("➕ Mathematics Marks", min_value=0, max_value=100, value=60)
science = st.slider("🔬 Science Marks", min_value=0, max_value=100, value=65)
english = st.slider("📖 English Marks", min_value=0, max_value=100, value=70)
st.divider()

# Calculating Total and Percentage
total_marks = maths + science + english
percentage = total_marks / 3

# Displaying the result on the screen
st.subheader("📊 Your Result Summary")

# Display data side by side using columns
col1, col2 = st.columns(2)
col1.metric(label="Total Marks Obtained", value=f"{total_marks} / 300")
col2.metric(label="Percentage", value=f"{percentage:.2f}%")

# Deciding grades Based on Percentage
if percentage >= 90:
    grade = "A+ (Outstanding) 🌟"
    color = "success"
elif percentage >= 80:
    grade = "A (Excellent) 👏"
    color = "success"
elif percentage >= 70:
    grade = "B (Very Good) 👍"
    color = "info"
elif percentage >= 60:
    grade = "C (Good) 👌"
    color = "info"
elif percentage >= 50:
    grade = "D (Pass) 📝"
    color = "warning"
else:
    grade = "F (Fail) ❌ Needs Improvement"
    color = "error"

# Displaying the Final Grade in a beautiful box
if color == "success":
    st.success(f"Final Grade: {grade}")
elif color == "info":
    st.info(f"Final Grade: {grade}")
elif color == "warning":
    st.warning(f"Final Grade: {grade}")
else:
    st.error(f"Final Grade: {grade}")

