# -*- coding: utf-8 -*-
"""Students Name List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pn_6blOE9PbI6hOICHzlSh2sITj3ueUX
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

#  Title of the app
st.title("🎒 Class Attendance & Student List")
st.write("Enter your name below to add yourself to the class list.")

# Storing the list of students in the session state
if "students" not in st.session_state:
    st.session_state.students = []

# Box and button for entering names (with Form)
# Clear_on_submit=True will clear the box upon pressing the button so the next student can enter their name.
with st.form("student_form", clear_on_submit=True):
    student_name = st.text_input("Enter Your Full Name:")
    submit_btn = st.form_submit_button("Add to List")

# When a student presses the "Add to List" button
if submit_btn:
    # Check if the name is empty
    if student_name.strip() == "":
        st.warning("⚠️ Please enter a valid name!")
    # Checking if this name is already listed (Duplicate Check)
    elif student_name.strip() in st.session_state.students:
        st.info(f"ℹ️ '{student_name}' is already in the list.")
    else:
        # add name to list
        st.session_state.students.append(student_name.strip())
        st.success(f"🎉 {student_name} has been added successfully!")

st.divider()

# Show live count of total number of students enrolled
total_students = len(st.session_state.students)
st.subheader(f"📊 Total Students Registered: {total_students}")

# Display a list of all students on the screen
if total_students > 0:
    st.write("📜 Student Roster:")

    # Showing names with numbers one by one
    for index, name in enumerate(st.session_state.students, start=1):
        st.write(f"**{index}.** {name}")
else:
    st.info("No students have entered their names yet. Be the first one!")