# -*- coding: utf-8 -*-
"""Student .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pW4qKIpTdkBspO68KaqDZ_gdN0_jqx6r
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Student Informations")

new_student = st.text_input("Student Name :")
roll_num = st.number_input("Enter The Roll Number")
courses = st.selectbox("Select Your Course", ("B.Tech","M.Tech","BBA","MBA","MCA","BCA"))
subjects = st.radio("Select subjects", ("hindi","english","math"))
marks = st.slider("Select your marks", 0, 100, 50)
if st.button("Student Information"):
  if new_student:
    st.success(f"Student Name : {new_student}")
    st.write(f"Roll Number: {roll_num}")
    st.write(f"Course: {courses}")
    st.write(f"Subjects: {subjects}")
    st.write(f"Marks: {marks}")
  else:
    st.warning("Please Enter a Valid Name")

  st.write("No names submitted yet")

