# -*- coding: utf-8 -*-
"""Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb4B9qc2wRc35p0V7u4SaDm6OZqj8jjt
"""

# Commented out IPython magic to ensure Python compatibility.
#  %pip install streamlit

import pandas as pd
import streamlit as st

# Heading of App
st.title("📊 Dynamic Table Generator")

# Getting the number of rows and columns from the user
rows = st.number_input("How many rows?", min_value=1, max_value=10, value=3)
cols = st.number_input("How many columns?", min_value=1, max_value=10, value=3)

# Creating the Generate button
if st.button("Generate Table"):

# Creating an empty Dictionary to store the data
  data={}

# creating column and row data by running a loop
  for c in range(cols):
    col_name =(f"Column{c +1}")   # The name of the column(e.g. column1)

# Enter sample data for each row within each
    data[col_name] = [f"Row {r+1},Col {c+1}" for r in range(rows)]

# Converting Dictionary to pandas DataFrame (Table)
  df = pd.DataFrame(data)

# Displaying tables beautifully on the screen
  st.subheader("Your Generated Table:")
  st.dataframe(df)

