# -*- coding: utf-8 -*-
"""To-Do List App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLNT6iLxsg6j7pYWdAM2rWuMg9RvXBAw

# To-Do List App
Store tasks using session state.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

# Import Streamlit library and give it short name "st"
import streamlit as st


# Creates main heading on webpage
st.title("To Do App")

# Check whether "tasks" list already exists
# in Streamlit session memory
if "tasks" not in st.session_state:

    # Create an empty list for storing tasks
    st.session_state.tasks=[]


# Create a text box to type task
# Store entered text inside variable task
task=st.text_input("Task")


# Create Add button
# Code runs only when button is clicked
if st.button("Add"):

    # Add entered task into task list
    st.session_state.tasks.append(task)


# Loop through every task in task list
for t in st.session_state.tasks:

    # Display task with check mark
    st.write("✅",t)

