# -*- coding: utf-8 -*-
"""Writefile app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfUpgh2h1VdkHrh0BjPIKh1lIOAMSf3g
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # paste full code here

# Commented out IPython magic to ensure Python compatibility.
# %pip install Streamlit
import streamlit as st

course = st.selectbox(
    "Select Course",
    ["BCA","BBA","MBA","MCA","other"]
)

if course=="other":
  name = st.text_input("Enter your name")

